extends SceneTree


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	root.size = Vector2i(1280, 720)
	var packed: PackedScene = load("res://scenes/main.tscn")
	var main: Control = packed.instantiate()
	root.add_child(main)
	await process_frame
	await process_frame
	var screen := main.get_child(0)
	assert(screen.get("dialogue_view") != null)
	assert(screen.get("recent_view") != null)
	assert(screen.get("info_button") != null)
	assert(screen.get("bag_button") != null)
	assert(screen.get("history_button") != null)
	assert(screen.get("rules_button") != null)
	assert(screen.get("status_button") != null)
	assert(screen.get("settings_button") != null)
	assert(screen.get("start_menu") != null)
	assert(screen.get("drawer") != null)
	assert(screen.get("rules_panel") != null)
	assert(screen.get("upgrade_panel") != null)
	assert(screen.get("progress_label") != null)
	assert(screen.get("npc_public_label") != null)
	assert(screen.get("card_grid") != null)
	assert(screen.get("background_texture") != null)
	assert(screen.get("player_portrait") != null)
	assert(screen.get("npc_portrait") != null)
	screen.state.choose_npc(0)
	screen.call("_set_current_npc_assets")
	var dialogue: Control = screen.get("dialogue_view")
	var recent: Control = screen.get("recent_view")
	var info_button: Control = screen.get("info_button")
	var settings_button: Control = screen.get("settings_button")
	var start_menu: Control = screen.get("start_menu")
	var drawer: Control = screen.get("drawer")
	var rules_panel: Control = screen.get("rules_panel")
	var settings_panel: Control = screen.get("settings_panel")
	var upgrade_panel: Control = screen.get("upgrade_panel")
	var modal_backdrop: Button = screen.get("modal_backdrop")
	var card_grid: Control = screen.get("card_grid")
	var background: TextureRect = screen.get("background_texture")
	var player_portrait: TextureRect = screen.get("player_portrait")
	var npc_portrait: TextureRect = screen.get("npc_portrait")
	var lower_box: TextureRect = screen.get("lower_box")
	var upper_box: TextureRect = screen.get("upper_box")
	var current_nameplate: TextureRect = screen.get("current_nameplate")
	var previous_nameplate: TextureRect = screen.get("previous_nameplate")
	var side_shadow_left: Control = screen.get("side_shadow_left")
	var side_shadow_right: Control = screen.get("side_shadow_right")
	assert(background.texture != null)
	assert(not background.texture.resource_path.ends_with("dialogue_base.png"))
	assert(player_portrait.texture != null)
	assert(npc_portrait.texture != null)
	assert(not player_portrait.visible)
	assert(not npc_portrait.visible)
	assert(player_portrait.flip_h)
	assert(lower_box != null)
	assert(upper_box != null)
	assert(current_nameplate != null)
	assert(previous_nameplate != null)
	assert(settings_panel != null)
	assert(side_shadow_left != null)
	assert(side_shadow_right != null)
	assert(modal_backdrop != null)
	assert(not side_shadow_left.visible)
	assert(not side_shadow_right.visible)
	assert(not lower_box.visible)
	assert(not upper_box.visible)
	assert(lower_box.z_index > player_portrait.z_index)
	assert(upper_box.z_index > npc_portrait.z_index)
	assert(not dialogue.scroll_active)
	assert(not recent.scroll_active)
	assert(dialogue.size.x > 480)
	assert(dialogue.size.y >= 45)
	assert(dialogue.global_position.y + dialogue.size.y <= 720)
	assert(recent.size.x > 500)
	assert(recent.size.y >= 40)
	assert(info_button.size.x >= 60)
	assert(info_button.global_position.x > 1160)
	assert(settings_button.global_position.x > 1160)
	assert(start_menu.visible)
	assert(start_menu.get("start_button") != null)
	assert(start_menu.get("rules_button") != null)
	assert(start_menu.get("settings_button") != null)
	var menu_start_button: Button = start_menu.get("start_button")
	var menu_rules_button: Button = start_menu.get("rules_button")
	var menu_settings_button: Button = start_menu.get("settings_button")
	assert(menu_start_button.size.x > menu_rules_button.size.x)
	menu_rules_button.emit_signal("pressed")
	await process_frame
	assert(rules_panel.visible)
	modal_backdrop.emit_signal("pressed")
	await process_frame
	menu_settings_button.emit_signal("pressed")
	await process_frame
	assert(settings_panel.visible)
	modal_backdrop.emit_signal("pressed")
	await process_frame
	assert(not drawer.visible)
	assert(not rules_panel.visible)
	assert(not upgrade_panel.visible)
	assert(card_grid.get_child_count() >= 2)
	screen._set_active_speaker("player")
	assert(is_equal_approx(npc_portrait.modulate.a, 1.0))
	assert(npc_portrait.modulate.r < 0.5)
	screen._set_active_speaker("npc")
	assert(is_equal_approx(player_portrait.modulate.a, 1.0))
	assert(player_portrait.modulate.r < 0.5)
	screen._set_dialogue_visible(true)
	assert(lower_box.visible)
	assert(player_portrait.visible)
	assert(npc_portrait.visible)
	assert(side_shadow_left.visible)
	assert(side_shadow_right.visible)
	screen._store_final_dialogue("NPC", "previous line")
	screen._show_previous_final_if_ready()
	await create_timer(0.35).timeout
	assert(upper_box.visible)
	assert(is_equal_approx(upper_box.modulate.a, 1.0))
	screen._set_current_dialogue_role("player")
	await create_timer(0.25).timeout
	assert(is_equal_approx(lower_box.scale.x, 1.0))
	info_button.emit_signal("pressed")
	await process_frame
	var intel_panel: Control = screen.get("intel_panel")
	assert(intel_panel != null)
	assert(intel_panel.visible)
	assert(modal_backdrop.visible)
	modal_backdrop.emit_signal("pressed")
	await process_frame
	assert(not intel_panel.visible)
	assert(not modal_backdrop.visible)
	root.size = Vector2i(390, 844)
	await process_frame
	await process_frame
	assert(menu_start_button.size.x <= 390)
	assert(menu_rules_button.size.x <= 390)
	assert(menu_rules_button.global_position.y + menu_rules_button.size.y <= menu_settings_button.global_position.y)
	assert(dialogue.size.x > 240)
	assert(dialogue.size.y >= 35)
	assert(dialogue.global_position.y + dialogue.size.y <= 844)
	screen.call_deferred("_on_start_pressed")
	await process_frame
	await process_frame
	assert(not start_menu.visible)
	assert(screen.get("running"))
	assert(screen.get("selection_panel").visible)
	print("LiarsLand visual layout checks passed.")
	quit(0)
